### ISSUE TITLE
What is the license of the code in this repo?

### ISSUE THREAD

**Issue by rafaelcaricio** [stevenlr/HandmadeRust#1]
Hi @stevenlr 

This is an awesome blog series that you've started. I'm learning a lot since I was trying to implement an stand-alone allocator for my project. I was wondering though, what is the license you are publishing this project? Can I use parts of this code in my open source project?

Cheers!

**Comment by stevenlr** [comment]
Hello and thanks for your interest in this project. :)

Everything is public domain, I've just added a license file to make it official, so feel free to use any of this. Though for obvious reasons I can't recommend anyone use this for anything serious without in-depth auditing, it's just a toy project.

Have fun!

**Comment by rafaelcaricio** [comment]
Thank you! :)
